pipeline {
  agent any

  tools {
    jdk 'JDK23'
    maven 'maven3'
  }

  options {
    // evita el checkout automático duplicado del declarative
    skipDefaultCheckout(true)
  }

  stages {
    stage('Checkout') {
      steps {
        // usa la config de SCM del job (ya apunta a tu repo)
        checkout scm
      }
    }

    stage('Build & Test') {
      steps {
        dir('CalculadoraACalidad') {
          bat 'mvn -B -DskipTests=false test'
        }
      }
    }
  }

  post {
    always {
      junit 'CalculadoraACalidad/target/surefire-reports/*.xml'
      archiveArtifacts artifacts: 'CalculadoraACalidad/target/*.jar',
                        allowEmptyArchive: true,
                        fingerprint: true
    }
  }
}

