pipeline {
  agent any

  tools {
    jdk 'JDK23'
    maven 'maven3'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/AnllyAnalyCastilloVilleda/ExamenAseguramientoCalidad.git'
      }
    }

    stage('Build & Test') {
      steps {
        bat 'mvn -B -DskipTests=false test'
      }
    }
  }

  post {
    always {
      junit '**/target/surefire-reports/*.xml'
      archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true, allowEmptyArchive: true
    }
  }
}
