pipeline {
    agent any

    tools {
        // Estos nombres deben coincidir con los configurados en Jenkins (Manage Jenkins > Global Tool Configuration)
        jdk    'jdk-23'
        maven  'maven3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/AnllyAnalyCastilloVilleda/ExamenAseguramientoCalidad.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
}
